feat: Specific feedback chat labels
justicecanada/otto pull request #39
Opened 2024-09-10 18:44 UTC by andrewkong9

Enabled different labels for the different chat tabs available. It is now clear which chat tab is getting feedback (e.g. Translate, Summarize, etc.).

2024-09-11 21:02 UTC, haitmo requested changes
Good job Andrew. Here are a few things that I think should be changed

2024-09-25 12:33 UTC, haitmo commented
Thanks Andrew!

Can you also:
- Add a quick test or supplement the existing one to take into account this new label?
- Merge the latest changes from main into this branch

2024-10-07 20:08 UTC, juleskuehn commented on django/otto/forms.py
> +            self.fields["app"].choices = [("document qa", _("Document QA"))]
this mode doesn't actually exist anymore

2024-10-08 13:51 UTC, juleskuehn approved these changes
Looks good! Feel free to merge.

2024-10-08 13:51 UTC, juleskuehn commented on .vscode/settings.json
> +  "python.testing.pytestEnabled": true
Not sure why these changes are needed, but I assume they won't cause issues for others. If so, we can remove them in another PR.

2024-10-08 13:55 UTC, juleskuehn approved these changes

2024-10-08 14:00 UTC, merged